# Generated by Django 5.0.2 on 2024-02-27 11:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_receipe_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='receipe',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
